project:
  type: website
  output-dir: docs

website:
  title: "Shannon Dickson"
  navbar:
    left:
      - href: index.qmd
      - about.qmd
      - pubs.qmd
format:
  html:
    theme:
      light: lux
      dark: slate
    css: styles.css
    toc: true

